### ISSUE TITLE
Please contact me

### ISSUE THREAD

**Issue by rene1980** [jsergio123/script.module.urlresolver#12]
Hello Jsergio!

Please I need  your help at our Community Project. Please contact me at gitter.im if you would like to help us.
Thanks a lot, Greets rene1980

Sorry me for this contact way, but there is no E-Mail here to do that

**Comment by TheAlpha12** [comment]
Can I have your bank account details please jsergio and your trannie tapes :)

**Comment by lastship** [comment]
good joke.....

**Comment by rene1980** [comment]
ohh,you are a Joker?

**Comment by jsergio123** [comment]
@TheAlpha12 you can have all the tapes except for the one of you. I'm keeping that one.

**Comment by rene1980** [comment]
Ok.I understand.you can not help us.No Problem.Good Luck for the future.Greets Rene

**Comment by jsergio123** [comment]
@rene1980 can you reach out to me on twitter and then we can discuss things further. Thank you.
