### ISSUE TITLE
[Settings] - Blank labels

### ISSUE THREAD

**Issue by Kr1ss-XD** [jsergio123/script.module.urlresolver#15]
The credentials fields for the SMOOZED universal resolver have no labels, confusing some users about what should be entered there.

<a href="http://www.directupload.net/file/u/69281/oy5xulsb_png.htm" target="_blank"><img src="http://fs5.directupload.net/images/user/170826/temp/oy5xulsb.png" border="1" alt="Gehostet von directupload.net"></a>

**Comment by jsergio123** [comment]
https://github.com/jsergio123/script.module.urlresolver/commit/a31ae60a8ea85a51cc1a54ce19bb935de090acc0
