### ISSUE TITLE
Alluc provider 

### ISSUE THREAD

**Issue by ebs111** [jsergio123/script.module.urlresolver#20]
hi 
great addon , kodi is realy worthless without it.
is there any way to add http://accounts.alluc.com/ to the URLResover so it will be set for all addons?
thanks for your help.

**Comment by jsergio123** [comment]
alluc is not a file host sorry

**Comment by ebs111** [comment]
Hi
Thanks for the replay
But it is, look here for example
http://www.alluc.ee/stream/Matrix
You can set alluc account in convenant for exàmpl
Plus it has its own addon
https://www.google.co.il/url?sa=t&source=web&rct=j&url=https://www.youtube.com/watch%3Fv%3DFV-6qUhf-UI&ved=0ahUKEwj39Krp6I_WAhVLPhQKHefrDfcQwaICCCkwAg&usg=AFQjCNFuv2ClNuhcQIFSfEEBA9RKh7NGVA

**Comment by Kr1ss-XD** [comment]
You are confusing file hoster and index site. Alluc is the latter.
The link you posted points to a page where links to several file hosters are listed.

**Comment by ebs111** [comment]
i understand,
but you can see what i mean here: 
https://www.youtube.com/watch?v=_g8r0b90Sq8

**Comment by Kr1ss-XD** [comment]
Yep that's the point. Video Addons like the one mentioned in the video scrape the index sites (like Alluc) for links to files on the hosters. These links are then passed to URLresolver.
So Alluc could be a plugin for a video Addon but not for URLresolver. It's simply not a hoster.

**Comment by ebs111** [comment]
so if i get it right the alluc link is send to the URLresolver?
if so there is aneed for login, and that is what i mean that the login will be in the URLresolver and not for every addon seperatly

**Comment by Kr1ss-XD** [comment]
No not e alluc link but the links that are scraped from the alluc site by the video Addon are passed to s.m.u.
E.g. links to gvjideo, openload, ...  These are the file hosters. Alluc doesn't host anything.

**Comment by jsergio123** [comment]
@Kr1ss-XD thanks for explaining it to him

**Comment by Kr1ss-XD** [comment]
NP.
Hope I was descriptive finally ;)
