### ISSUE TITLE
please fix thevid

### ISSUE THREAD

**Issue by antrrax** [jsergio123/script.module.urlresolver#22]
thevid stopped working, just playing this video:
http://thevid.net/player/r.mp4

link example: http://thevid.net/e/dlk4uoni0ng63e1ysv46qvb5x
tested kodi 16 and 17

**Comment by jsergio123** [comment]
https://github.com/jsergio123/script.module.urlresolver/commit/b9767c1252f4f4c2312332acda7cd30bd4311704

**Comment by antrrax** [comment]
Thank you very much, I am grateful for your commitment to mater this script always working!
