### ISSUE TITLE
Streamango Plug is off

### ISSUE THREAD

**Issue by firerm** [jsergio123/script.module.urlresolver#23]
Streamango is off ... Embed code changed ?

**Comment by bugatsinho** [comment]
probably the file is deleted...can you provide the link?

**Comment by firerm** [comment]
*****stream ango.com/f/keepcdradcnotpdn/8askoto8w

**Comment by firerm** [comment]
and with https    *****stream ango.com/f/crlkoqtekppdplkp/tzak both of them not "resolving "

**Comment by firerm** [comment]
I remove the link for security reasons  ...

**Comment by jsergio123** [comment]
They have started to encrypt their url's with JS now. I have to crack it.

**Comment by bugatsinho** [comment]
p.a.c.k.e.r

**Comment by NitroXenon** [comment]
Just found that they're using DASH now.

**Comment by jsergio123** [comment]
they use DASH and HLS as a fallback both are encrypted

**Comment by zbyna** [comment]
I tried to translate it  to python with: https://github.com/PiotrDabkowski/Js2Py
but it does not look better: https://pastebin.com/kxGR2GEN

**Comment by jsergio123** [comment]
I have included js2py to handle this but it comes at some risk. I have filtered eval() from the remote code being translated so hopefully it is safe to use. USE AT YOUR OWN RISK. You can disable this plugin in the url resolver settings if you want.
