### ISSUE TITLE
Vidoza.net 

### ISSUE THREAD

**Issue by critterskins** [jsergio123/script.module.urlresolver#24]
Old links still working new links messed up but the link is definitely good

**Comment by jsergio123** [comment]
can you provide me with the url you are having problems resolving minus the http://

**Comment by critterskins** [comment]
vidoza.net/vjpd77d7457l.html

**Comment by jsergio123** [comment]
The plugin is still working correctly. The file you posted shows the video is in queue for being processed by vidoza so it's not available yet. 

> ->{lng_download_video_processing_now} Pending in queue #794

**Comment by critterskins** [comment]
Sorry to waste your time I should have looked more carefully

**Comment by jsergio123** [comment]
You didn't waste my time. It's not a problem. Thank you for raising issues for the url resolver. Please continue to do so.
