### ISSUE TITLE
[bug] Vdizella.me - Open - error probing input format

### ISSUE THREAD

**Issue by Philps** [jsergio123/script.module.urlresolver#25]
INFO: XCURL::DllLibCurlGlobal::easy_aquire - Created session to https://vidzella.me
	Line 974: 16:09:42.107 T:7300   DEBUG: CCurlFile::GetMimeType - https://vidzella.me/play#J2YL -> x-directory/normal
	Line 975: 16:09:42.116 T:7300   DEBUG: Loading settings for https://vidzella.me/play#J2YL
	Line 976: 16:09:42.127 T:7300   DEBUG: CPlayerCoreFactory::GetPlayers(https://vidzella.me/play#J2YL)
	Line 998: 16:09:42.132 T:7300  NOTICE: VideoPlayer: Opening: https://vidzella.me/play#J2YL
	Line 1000: 16:09:42.273 T:7300   DEBUG: CCurlFile::GetMimeType - https://vidzella.me/play#J2YL -> x-directory/normal
	Line 1005: 16:09:42.275 T:9852   DEBUG: CurlFile::Open(0EA8F084) https://vidzella.me/play#J2YL
	Line 1006: 16:09:42.626 T:9852   DEBUG: CCurlFile::Open - effective URL: <https://vidzella.me/play/>
	Line 1008: 16:09:42.634 T:9852   DEBUG: CurlFile::Open(0C7C7158) https://vidzella.me/play/
	Line 1013: 16:09:42.908 T:9852   ERROR: CDVDDemuxFFmpeg::Open - error probing input format, https://vidzella.me/play/

**Comment by Philps** [comment]
please remove the https tags [url] once seen. thx

**Comment by sdfwv** [comment]
if you change the url

```
# from
https://vidzella.me/play#J2YL
# to
https://vidzella.me/play/#J2YL
```

it should work

_tested with https://github.com/Colossal1/plugin.video.link__tester_

not sure where you got the link without **/**

**Comment by jsergio123** [comment]
"/play#{media_id"} does indeed redirect to "/play/#{media_id}" so I added support for it in this commit. Thanks guys. https://github.com/jsergio123/script.module.urlresolver/commit/07a7b9aba2c033cd2d90c45912fdc5d31fadc1e2
