### ISSUE TITLE
[URLResolver 4.0.04/Covenant] Latest URL Resolver introduces delays in some Covenant processes.

### ISSUE THREAD

**Issue by rpkodi** [jsergio123/script.module.urlresolver#31]
The latest version of URL Resolver 4.0.04 seems to have introduced delays ~10 seconds each, before the search process launches after selecting a TV episode, and then in displaying streams after the search process has completed, and finally in launching a selected stream. All other processes seem normal. Have switched back and forth between 4.0.02 and 4.0.04 several times and confirmed Covenant 1.1.14 functions flawlessly with 4.0.02. I am using an RPi 2 and PC and noticed the delays mostly with the Rpi so it would seem likely that slower boxes with less RAM accentuate this issue much more. All versions of URL Resolver up to 4.0.02 and Covenant work flawlessly and fast on the RPi 2 therefore definitely not the box or other factor.

**Comment by KoDiGo14** [comment]
Covenant search links isnt connected with smu...smu is used to resolve the links...so smu it takes place after you click the link to play...covenant search links process it tooks to start on my nvidia shield at the first time 5" and you are right on that,but im not sure how relevant is with smu!probably sergio knows better

**Comment by rpkodi** [comment]
I understand that, but the fact is the update directly affects Covenant in the ways I described so it could be something like a memory leak that is impacting boxes with a gig of RAM - it is definitely a significant slow down anyway.

**Comment by jsergio123** [comment]
@rpkodi delete the js2py folder and the streamango.py from your device that is having the issue and let me know if you see any difference. I'm not seeing any issues on Windows or Android. Please post a debug log using pastebin.

**Comment by antrrax** [comment]
Here I use Kodi 16 on an android system [4.4.2] with 1GB of Ram, and use Kodi 16 on windows 8.1 to create my add-ons. The most used urlresolver is Thevid.

On windows everything works normal as expected.
On Android I'm having problems:

On Android - This does not work:

def addLink (...
	liz = xbmcgui.ListItem (name, iconImage = "DefaultVideo.png", thumbnailImage = iconimage)
	liz.setProperty ('IsPlayable', 'true')
---------------

def player (...
	xbmcplugin.setResolvedUrl (int (sys.argv [1]), False, listitem)
---------------

With such a code, it does not play the video.

########################

On Android - this works:
def addLink (...
	liz = xbmcgui.ListItem (name, iconImage = "DefaultVideo.png", thumbnailImage = iconimage)

	#I disable this:
	# liz.setProperty ('IsPlayable', 'true')
	# +++++++
---------------
def player (...
	liz = xbmcgui.ListItem (name, iconImage = "DefaultVideo.png", thumbnailImage = iconimage)

	#I disable this:
	# xbmcplugin.setResolvedUrl (int (sys.argv [1]), False, listitem)
	# +++++++

	xbmcPlayer = xbmc.Player ()
	xbmcPlayer.play (item = stream_url, listitem = listitem)
---------------

With this code the video plays, but does not interact correctly with the database of kodi, to show icon of watched and movie quality.

However, when I removed the js2py folder and the file streamango.py, as was suggested.
The system returned to work normally on Android with 1GB RAM, and first code above.

**Comment by rpkodi** [comment]
I could not locate the js2py folder on my Kodi 17.3 system - LibreELEC - although it exists on Kodi 16.1 on my PC. I deleted streamango.py but did not seem to make any difference. to the issues described.

[Here is the debug log requested:] (https://pastebin.com/f9vGypxH)

I noticed that URL Resolver initialised three times in as many minutes, not sure if this is normal.

Whatever the issue, after further tests there is no doubt that on my 1GB Rpi 2 that updating to URL Resolver 4.0.04 causes these delays in the stream selection processes.

Thanks.

**Comment by bjgood** [comment]
I was experiencing the same problem (Pi3...LibreELEC 8.1.1). I deleted the js2py folder and file streamango.py from the 4.0.04 zip file itself, and installed it. Delay problem solved.

**Comment by antrrax** [comment]
`/storage/sdcard0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urlresolver/js2py
`
'.kodi' is hidden folder

**Comment by jsergio123** [comment]
https://github.com/jsergio123/script.module.urlresolver/commit/9359bdf685d46dda878883b56bd82af5c4e2ef7d

**Comment by bugatsinho** [comment]
rpkodi  try to disable the autocleaner you use on your kodi and rerun kodi and covenant!that delay it happens only on first time you search for a movie sources right?
