### ISSUE TITLE
XVidStage plugin

### ISSUE THREAD

**Issue by Kr1ss-XD** [jsergio123/script.module.urlresolver#38]
In reference to PR https://github.com/jsergio123/script.module.urlresolver/pull/37#event-1252615254

Thx

**Comment by jsergio123** [comment]
https://github.com/jsergio123/script.module.urlresolver/commit/8a933ec90c929c0b0a35b56c4d58fca7d5b43f30

**Comment by Kr1ss-XD** [comment]
Yep working again on my end too.  
Thank u !
