### ISSUE TITLE
Streamcherry

### ISSUE THREAD

**Issue by zm1c4l** [jsergio123/script.module.urlresolver#39]
You forgot to do a patch in the streamcherry plugin. Streamango and Streamcherry are twin hosting.

**Comment by jsergio123** [comment]
Both sites are broken. I will contact them to see if they wish to do pairing but if not I will be removing them.

**Comment by jsergio123** [comment]
Yes. I haven't really looked into much but after a quick glance it seems like the p,a,c,k,e,r isn't being unpacked correctly.

**Comment by firerm** [comment]
It's possible to fix it ? Streamango never has no buffering issues so will be a very stable host for movies. Thanks For the info :)

**Comment by jsergio123** [comment]
Yes I have already fixed it but not sure what to do with it.

**Comment by jsergio123** [comment]
Fixed but make sure you delete the streamcherry.py too https://github.com/jsergio123/script.module.urlresolver/commit/7b37a277387a3d52f01c68909dbca788a0c74137
