### ISSUE TITLE
please add bitporno.com

### ISSUE THREAD

**Issue by Philps** [jsergio123/script.module.urlresolver#47]
seems to be porn provider but is being used as stream hoster as well.

supports mkv format and dd 5.1

**Comment by Colossal1** [comment]
BitPorno is located under the xxx smu extention. It would be for the addons to import the modules from there to support bitporno.

**Comment by jsergio123** [comment]
added https://github.com/jsergio123/script.module.urlresolver.xxx/commit/56ba3dba3b334a1e4d9e49cc49d9bd39a6ea51e9
