### ISSUE TITLE
flashx.tv new trailer2.mp4

### ISSUE THREAD

**Issue by kodistuff1** [jsergio123/script.module.urlresolver#60]
works for me: update `fx_gmu.py` line 57 to add "trailer2.mp4" to the blacklist

```
sources = helpers.scrape_sources(html, patterns=["""src:\s*["'](?P<url>[^"']+).+?res:\s*["']?(?P<label>\d+)"""], result_blacklist=["trailer.mp4","trailer2.mp4"], generic_patterns=False)
```

Also, flashx now has a pairing solution, but you need a flashx account to do it...

https://www.flashx.tv/pairing.php

**Comment by jsergio123** [comment]
Yes I know. I am implementing pairing for flashx already with them.

**Comment by kodistuff1** [comment]
Good stuff - thought about doing that as well, but honestly, requiring an account seemed such a poor idea that I couldn't see anyone actually using it...

**Comment by jsergio123** [comment]
I agree requiring an account is a poor choice but I'm tired of fixing it everyday so pairing it is.

**Comment by jsergio123** [comment]
@kodistuff1 make the PR and I'll merge it.
