### ISSUE TITLE
GVideo HTTP returned error 403

### ISSUE THREAD

**Issue by kvl19** [jsergio123/script.module.urlresolver#62]
It seems like there is a short google link, I can access that with my browser, but somehow the addon is trying to access the long link, which I cannot open in my browser. Is it possible that URLResolver is resolving the short URL into the long URL/wrong link?

> 

13:10:32.970 T:140195978536704 NOTICE: URLResolver: Initializing URLResolver version: 4.0.08 

13:10:50.631 T:140197893719808 NOTICE: Previous line repeats 1 times. 

13:10:50.631 T:140197893719808 WARNING: Attempt to use invalid handle -1 

13:10:50.863 T:140198917851520 NOTICE: VideoPlayer: Opening: https://lh3.googleusercontent.com/fzwk81cATOb3wi5f5wk7DQlAsWctALUZxPmfzvI8d68Oi7ONzpGeehz5240znEKw4mx5efXbLUA=m22 

13:10:50.863 T:140198917851520 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED 

13:10:51.008 T:140195978536704 NOTICE: Creating InputStream 

13:10:51.861 T:140195978536704 ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403 

13:10:51.861 T:140195978536704 ERROR: CCurlFile::Open failed with code 403 for https://r13---sn-ab5l6ney.c.lh3.googleusercontent.com/videoplayback?id=2b98fc26ae8e9a72&itag=22&source=webdrive&begin=0&requiressl=yes&mm=30&mn=sn-ab5l6ney&ms=nxu&mv=m&pl=24&sc=yes&ei=m_T9WdqSDtb--AWtxYCwAg&app=fife&driveid=0B2Pd0OiL5SPhaUhJeTJrNHRqQ28&mime=video/mp4&lmt=1509674528142430&mt=1509815374&ip=196.52.2.76&ipbits=8&expire=1509822651&cp=TUlLWVNRX1VVT0JCSTpFSWs3QmQzUWVTd1NXeWVyUjJzMlNWQ0w5VWFYRFlBNTZuT29DSE9Lb3dmTjhmbFJ1eXFEa3JZZXNZTXFUcGU&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,sc,ei,app,driveid,mime,lmt,cp&signature=6F30371BB27E0096F026ABAAABCA7820E9DFA691.3232F3F0F5FFAA2DB7DB57791CB9F7CA9373834B&key=ck2 

13:10:51.862 T:140195978536704 ERROR: Open - failed to open source https://r13---sn-ab5l6ney.c.lh3.googleusercontent.com/videoplayback?id=2b98fc26ae8e9a72&itag=22&source=webdrive&begin=0&requiressl=yes&mm=30&mn=sn-ab5l6ney&ms=nxu&mv=m&pl=24&sc=yes&ei=m_T9WdqSDtb--AWtxYCwAg&app=fife&driveid=0B2Pd0OiL5SPhaUhJeTJrNHRqQ28&mime=video/mp4&lmt=1509674528142430&mt=1509815374&ip=196.52.2.76&ipbits=8&expire=1509822651&cp=TUlLWVNRX1VVT0JCSTpFSWs3QmQzUWVTd1NXeWVyUjJzMlNWQ0w5VWFYRFlBNTZuT29DSE9Lb3dmTjhmbFJ1eXFEa3JZZXNZTXFUcGU&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,sc,ei,app,driveid,mime,lmt,cp&signature=6F30371BB27E0096F026ABAAABCA7820E9DFA691.3232F3F0F5FFAA2DB7DB57791CB9F7CA9373834B&key=ck2 

13:10:51.862 T:140195978536704 ERROR: CVideoPlayer::OpenInputStream - error opening [https://lh3.googleusercontent.com/fzwk81cATOb3wi5f5wk7DQlAsWctALUZxPmfzvI8d68Oi7ONzpGeehz5240znEKw4mx5efXbLUA=m22] 

13:10:51.862 T:140195978536704 NOTICE: CVideoPlayer::OnExit() 

13:10:51.885 T:140198917851520 NOTICE: CVideoPlayer::CloseFile() 

13:10:51.885 T:140198917851520 NOTICE: VideoPlayer: waiting for threads to exit 

13:10:51.885 T:140198917851520 NOTICE: VideoPlayer: finished waiting 

13:10:51.891 T:140198917851520 NOTICE: CVideoPlayer::CloseFile() 

13:10:51.891 T:140198917851520 NOTICE: VideoPlayer: waiting for threads to exit 

13:10:51.891 T:140198917851520 NOTICE: VideoPlayer: finished waiting 

13:12:09.461 T:140198917851520 NOTICE: Samba is idle. Closing the remaining connections*

**Comment by rmj35** [comment]
Me too! I can't play gvideo links anymore. I keep getting http error 403... 😭

**Comment by jsergio123** [comment]
Fixed https://github.com/jsergio123/script.module.urlresolver/commit/479279a55f200396aebe04f22882ebeaa554cce6
