### ISSUE TITLE
How to get my site in supported site list?

### ISSUE THREAD

**Issue by h4rpreet** [jsergio123/script.module.urlresolver#63]
Hi, i want to get my site whitelisted, i tried to find alot but i did not found any way to do so i am posting here. Can you please help me ?

**Comment by jsergio123** [comment]
Are you trying to add your site to this project? If so what is the url for you site?

**Comment by h4rpreet** [comment]
Yes, Basically we have a video host and we get lots of leeching via kodi, i asked my tech guy and he said we can do like how thevideo.me do , https://thevideo.io/pair.  For this he told me to contact kodi guys so they can ping to our special url so we can somewhat control this leeching. 

 I am not sure if i should contact you or kodi's owners. He showed me your plugin so i am contacting you first maybe you can help. Our host is vidlox.tv

**Comment by jsergio123** [comment]
Yes I am the one who can implement pairing for your site. Please contact me privately via unseen.is or keybase.io to discuss it further.
