### ISSUE TITLE
Real-Debrid Failed

### ISSUE THREAD

**Issue by rmj35** [jsergio123/script.module.urlresolver#65]
Every Real-Debrid link that works... Only last a few seconds then stops sometimes the video wont even show just name of the movie and the play icon at the top. I was only able to use real debrid with the Bubbles Addon. You'd have to choose "real-debrid" instead of UrlResolver. 

Please fix 😓
Thanks!

**Comment by jsergio123** [comment]
Real-Debird is working as it should. Your issues are not related to the UrlResolver.
