### ISSUE TITLE
request:ustream resolver

### ISSUE THREAD

**Issue by KoDiGo14** [jsergio123/script.module.urlresolver#9]
i would like to ask if it is possible to create a ustream resolver!thanks

**Comment by jsergio123** [comment]
I will try to when I get some free time

**Comment by KoDiGo14** [comment]
no problem mate!

**Comment by jsergio123** [comment]
Here, this won't work for live stream though. Live stream dont belong in the urlresolver. You need both of these commits for it to work.
https://github.com/jsergio123/script.module.urlresolver/commit/30e8fb1bd074f1ade65cc492082087f4fef9c2a9
https://github.com/jsergio123/script.module.urlresolver/commit/89e5c8d5462fb3227b43a03c10a5893d1cf22603
